---
# TODO: later need to add this as well with sudoers, this below is an example but change it to what is needed specifically for this k8slab setup!
# TODO: this is also for adding the public key and private key on the mgmt-vm if not already for example, etc.
# - name: Create groups
#   ansible.builtin.group: name={{ item.groupname }} state=present
#   with_items: "{{ as_groups }}"

# - name: Create user groups
#   ansible.builtin.group: name={{ item.username }} state=present
#   when: item['group'] == item['username']
#   with_items: "{{ users }}"

# - name: Cleanup Sudo group files
#   ansible.builtin.file: path=/etc/sudoers.d/{{ item.groupname }} state=absent
#   when: item['use_sudo'] == False
#   with_items: "{{ as_groups }}"

# - name: Cleanup Sudo group files Part 2
#   ansible.builtin.file: path=/etc/sudoers.d/{{ item.username }} state=absent
#   when: (item['use_sudo'] == False and item['group'] == item['username'])
#   with_items: "{{ users }}"

# - name: Create Sudo group files
#   ansible.builtin.lineinfile:
#     "dest=/etc/sudoers.d/{{ item.groupname }} # pragma: allowlist secret
#     create=True
#     regexp='^'
#     line='%{{ item.groupname }} ALL=(ALL) NOPASSWD: ALL'
#     state=present"
#   when: item['use_sudo'] == True
#   with_items: "{{ as_groups }}"

# - name: Add users | create users, shell, home dirs
#   ansible.builtin.user: name={{ item.username }} shell=/bin/bash createhome=yes comment='{{ item.desc }}' group={{ item.group }}
#   with_items: "{{users}}"

# - name: Setup | authorized key upload
#   ansible.posix.authorized_key: user={{ item.username }} key="{{ lookup('file', 'files/pub_keys/{{ item.username }}.pub') }}"
#   with_items: "{{ users }}"

# - name: Sudoers | extra sudo users
#   ansible.builtin.lineinfile: "dest=/etc/sudoers.d/{{ item.username }}
#     create=True
#     regexp='^'
#     line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
#     state=present"
#   when: (item['group'] == item['username'] and item['use_sudo'] == True) # {{ item.use_sudo }} uitlees workaround
#   with_items: "{{users}}"
