---
# handlers file for roles/jump_host

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Reload audit rules
  ansible.builtin.command:
    cmd: augenrules --load
  changed_when: true

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
